USE morudb;

DROP TABLE IF EXISTS `USER_FOOD_CALENDAR_TB`;
DROP TABLE IF EXISTS `TEMPLATE_FOOD_LIST_TB`;
DROP TABLE IF EXISTS `TEMPLATE_FOOD_TB`;
DROP TABLE IF EXISTS `TEMPLATE_ACTIVITE_LIST_TB`;
DROP TABLE IF EXISTS `TEMPLATE_ACTIVITE_TB`;
DROP TABLE IF EXISTS `USER_ACTIVITE_CALENDAR_TB`;
DROP TABLE IF EXISTS `USER_ACTIVITE_TB`;





DROP TABLE IF EXISTS `COMMENT_NOTICE_TB`;
DROP TABLE IF EXISTS `BOARD_NOTICE_TB`;

DROP TABLE IF EXISTS `COMMENT_FREE_TB`;
DROP TABLE IF EXISTS `BOARD_FREE_TB`;

DROP TABLE IF EXISTS `COMMENT_FEEDBACK_TB`;
DROP TABLE IF EXISTS `BOARD_FEEDBACK_TB`;

DROP TABLE IF EXISTS `BOARD_FILE_TB`;



DROP TABLE IF EXISTS `DIARY_HASHTAG_LINK_TB`;
DROP TABLE IF EXISTS `DIARY_HASHTAG_TB`;

DROP TABLE IF EXISTS `DIARY_LIKE_TB`;

DROP TABLE IF EXISTS `DIARY_WALK_FILE_TB`;
DROP TABLE IF EXISTS `DIARY_WALK_TB`;



DROP TABLE IF EXISTS `PET_WEIGHT_TB`;
DROP TABLE IF EXISTS `PET_INFO_TB`;
DROP TABLE IF EXISTS `PET_BREED_TB`;

DROP TABLE IF EXISTS `USER_EMAIL_CODE_TB`;
DROP TABLE IF EXISTS `USER_REFRESH_TOKEN_TB`;
DROP TABLE IF EXISTS `USER_WEIGHT_TB`;
DROP TABLE IF EXISTS `USER_INFO_TB`;

CREATE TABLE `USER_INFO_TB` (# 회원 
`UI_ID`VARCHAR(255) NOT NULL,# 유저 아이디
`UI_NICKNAME` VARCHAR(50) NOT NULL,# 닉네임
`UI_DEL` CHAR(1) NOT NULL DEFAULT 'N',# 삭제
`UI_POINT`INT NOT NULL DEFAULT 0,# 포인트
`UI_REGIST`DATETIME NOT NULL DEFAULT NOW(),# 가입일
`UI_PASSWORD` VARCHAR(300) NULL,# 비밀번호
`UI_EMAIL`VARCHAR(255) NULL,# 이메일
`UI_HEIGHT`INT NULL,# 키
`UI_AGE` INT NULL,# 나이
`UI_GENDER`VARCHAR(1) NULL,# 성별
`UI_ROLE` VARCHAR(20) NOT NULL# 권한
);

ALTER TABLE `USER_INFO_TB` ADD CONSTRAINT `USER_INFO_UI_ID_PK` PRIMARY KEY (`UI_ID`);

CREATE TABLE `USER_WEIGHT_TB` (# 회원 체중관리
`UW_NUM` INT NOT NULL,# 번호
`UI_ID`VARCHAR(255) NOT NULL,# 유저 아이디
`UW_DATE` DATE NOT NULL,# 날짜
`UW_WEIGHT`INT NOT NULL,# 몸무게
`UW_BODY_FAT` INT NOT NULL,# 체지방
`UW_MUSCLE`INT NOT NULL# 골격근
);

ALTER TABLE `USER_WEIGHT_TB` ADD CONSTRAINT `USER_WEIGHT_UW_NUM_PK` PRIMARY KEY (`UW_NUM`);
ALTER TABLE `USER_WEIGHT_TB` MODIFY `UW_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `USER_WEIGHT_TB` ADD CONSTRAINT `USER_WEIGHT_UI_ID_FK` FOREIGN KEY (`UI_ID`) REFERENCES USER_INFO_TB(UI_ID);

CREATE TABLE `USER_REFRESH_TOKEN_TB` (# 리프레쉬 토큰 관리
`URT_TOKEN`VARCHAR(500) NOT NULL,# 토큰
`UI_ID`VARCHAR(255) NOT NULL,# 유저 아이디
`UI_NICKNAME` VARCHAR(50) NOT NULL,# 닉네임
`UI_EMAIL`VARCHAR(255) NULL,# 이메일
`URT_KEEP_LOGIN` INT(1) NOT NULL DEFAULT 0,# 로그인 유지
`EXPIRATION` VARCHAR(50) NOT NULL
);

ALTER TABLE `USER_REFRESH_TOKEN_TB` ADD CONSTRAINT `USER_REFRESH_TOKEN_URT_TOKEN_PK` PRIMARY KEY (`URT_TOKEN`);

CREATE TABLE `USER_EMAIL_CODE_TB` (# 인증번호 관리
`UEC_NUM` INT NOT NULL,# 번호
`UEC_CODE` VARCHAR(6) NOT NULL# 코드
);

ALTER TABLE `USER_EMAIL_CODE_TB` ADD CONSTRAINT `USER_EMAIL_CODE_UEC_NUM_PK` PRIMARY KEY (
`UEC_NUM`
);
ALTER TABLE `USER_EMAIL_CODE_TB` MODIFY `UEC_NUM` INT NOT NULL AUTO_INCREMENT;




CREATE TABLE `BOARD_NOTICE_TB` (									# 공지게시판
	`BO_NUM`	INT	NOT NULL, 					# 게시판 번호
	`UI_ID`	VARCHAR(255)	NOT NULL,							# 회원 아이디
	`BO_TITLE`	VARCHAR(255)	NOT NULL,						# 게시판 제목
	`BO_CONTENT`	TEXT	NOT NULL,								# 게시판 내용
	`BO_WRITER`	VARCHAR(255)	NOT NULL,						# 작성자
	`BO_REPLY`	INT	NOT NULL,		# 답글 번호
	`BO_REPLY_DEPT`	INT	NOT NULL	DEFAULT 0,				# 답글 뎁스
	`BO_REGIST`	DATETIME	NOT NULL	DEFAULT NOW(),				# 작성일
	`BO_VIEW`	INT	NOT NULL	DEFAULT 0,						# 조회수
	`BO_DEL`	CHAR(1)	NOT NULL	DEFAULT 'N'						# 삭제여부
);

ALTER TABLE `BOARD_NOTICE_TB` ADD CONSTRAINT `BOARD_NOTICE_BO_NUM_PK` PRIMARY KEY (`BO_NUM`);
ALTER TABLE `BOARD_NOTICE_TB` MODIFY `BO_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `BOARD_NOTICE_TB` ADD CONSTRAINT `BOARD_NOTICE_UI_ID_FK` FOREIGN KEY (`UI_ID`) REFERENCES USER_INFO_TB(UI_ID);


CREATE TABLE `COMMENT_NOTICE_TB` (									# 공지게시판 댓글
	`CO_NUM`	INT	NOT NULL,					# 댓글 번호
	`BO_NUM`	INT	NOT NULL,										# 게시글 번호
	`UI_ID`	VARCHAR(255)	NOT NULL,							# 회원 아이디
	`CO_REPLY`	INT	NOT NULL,		# 답글 번호
	`CO_REPLY_DEPT`	INT	NOT NULL	DEFAULT 0,				# 답글 뎁스
	`CO_REGIST`	DATETIME	NOT NULL	DEFAULT NOW(),				# 작성일
	`CO_DEL`	CHAR(1)	NOT NULL	DEFAULT 'N',					# 삭제여부
	`CO_CONTENT`	VARCHAR(500)	NOT NULL						# 글내용
);
ALTER TABLE `COMMENT_NOTICE_TB` ADD CONSTRAINT `COMMENT_NOTICE_CO_NUM_PK` PRIMARY KEY (`CO_NUM`);
ALTER TABLE `COMMENT_NOTICE_TB` MODIFY `CO_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `COMMENT_NOTICE_TB` ADD CONSTRAINT `COMMENT_NOTICE_BO_NUM_FK` FOREIGN KEY (`BO_NUM`) REFERENCES BOARD_NOTICE_TB(BO_NUM);
ALTER TABLE `COMMENT_NOTICE_TB` ADD CONSTRAINT `COMMENT_NOTICE_UI_ID_FK` FOREIGN KEY (`UI_ID`) REFERENCES USER_INFO_TB(UI_ID);


CREATE TABLE `BOARD_FREE_TB` (									# 자유게시판
	`BO_NUM`	INT	NOT NULL, 					# 게시판 번호
	`UI_ID`	VARCHAR(255)	NOT NULL,							# 회원 아이디
	`BO_TITLE`	VARCHAR(255)	NOT NULL,						# 게시판 제목
	`BO_CONTENT`	TEXT	NOT NULL,								# 게시판 내용
	`BO_WRITER`	VARCHAR(255)	NOT NULL,						# 작성자
	`BO_REPLY`	INT	NOT NULL,		# 답글 번호
	`BO_REPLY_DEPT`	INT	NOT NULL	DEFAULT 0,				# 답글 뎁스
	`BO_REGIST`	DATETIME	NOT NULL	DEFAULT NOW(),				# 작성일
	`BO_VIEW`	INT	NOT NULL	DEFAULT 0,						# 조회수
	`BO_DEL`	CHAR(1)	NOT NULL	DEFAULT 'N'						# 삭제여부
);

ALTER TABLE `BOARD_FREE_TB` ADD CONSTRAINT `BOARD_FREE_BO_NUM_PK` PRIMARY KEY (`BO_NUM`);
ALTER TABLE `BOARD_FREE_TB` MODIFY `BO_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `BOARD_FREE_TB` ADD CONSTRAINT `BOARD_FREE_UI_ID_FK` FOREIGN KEY (`UI_ID`) REFERENCES USER_INFO_TB(UI_ID);


CREATE TABLE `COMMENT_FREE_TB` (									# 자유게시판 댓글
	`CO_NUM`	INT	NOT NULL,					# 댓글 번호
	`BO_NUM`	INT	NOT NULL,										# 게시글 번호
	`UI_ID`	VARCHAR(255)	NOT NULL,							# 회원 아이디
	`CO_REPLY`	INT	NOT NULL,		# 답글 번호
	`CO_REPLY_DEPT`	INT	NOT NULL	DEFAULT 0,				# 답글 뎁스
	`CO_REGIST`	DATETIME	NOT NULL	DEFAULT NOW(),				# 작성일
	`CO_DEL`	CHAR(1)	NOT NULL	DEFAULT 'N',					# 삭제여부
	`CO_CONTENT`	VARCHAR(500)	NOT NULL						# 글내용
);
ALTER TABLE `COMMENT_FREE_TB` ADD CONSTRAINT `COMMENT_FREE_CO_NUM_PK` PRIMARY KEY (`CO_NUM`);
ALTER TABLE `COMMENT_FREE_TB` MODIFY `CO_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `COMMENT_FREE_TB` ADD CONSTRAINT `COMMENT_FREE_BO_NUM_FK` FOREIGN KEY (`BO_NUM`) REFERENCES BOARD_FREE_TB(BO_NUM);
ALTER TABLE `COMMENT_FREE_TB` ADD CONSTRAINT `COMMENT_FREE_UI_ID_FK` FOREIGN KEY (`UI_ID`) REFERENCES USER_INFO_TB(UI_ID);



CREATE TABLE `BOARD_FEEDBACK_TB` (									# 피드백게시판
	`BO_NUM`	INT	NOT NULL, 					# 게시판 번호
	`UI_ID`	VARCHAR(255)	NOT NULL,							# 회원 아이디
	`BO_TITLE`	VARCHAR(255)	NOT NULL,						# 게시판 제목
	`BO_CONTENT`	TEXT	NOT NULL,								# 게시판 내용
	`BO_WRITER`	VARCHAR(255)	NOT NULL,						# 작성자
	`BO_REPLY`	INT	NOT NULL,		# 답글 번호
	`BO_REPLY_DEPT`	INT	NOT NULL	DEFAULT 0,				# 답글 뎁스
	`BO_REGIST`	DATETIME	NOT NULL	DEFAULT NOW(),				# 작성일
	`BO_VIEW`	INT	NOT NULL	DEFAULT 0,						# 조회수
	`BO_DEL`	CHAR(1)	NOT NULL	DEFAULT 'N'						# 삭제여부
);

ALTER TABLE `BOARD_FEEDBACK_TB` ADD CONSTRAINT `BOARD_FEEDBACK_BO_NUM_PK` PRIMARY KEY (`BO_NUM`);
ALTER TABLE `BOARD_FEEDBACK_TB` MODIFY `BO_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `BOARD_FEEDBACK_TB` ADD CONSTRAINT `BOARD_FEEDBACK_UI_ID_FK` FOREIGN KEY (`UI_ID`) REFERENCES USER_INFO_TB(UI_ID);


CREATE TABLE `COMMENT_FEEDBACK_TB` (									# 피드백게시판 댓글
	`CO_NUM`	INT NOT NULL,					# 댓글 번호
	`BO_NUM`	INT NOT NULL,										# 게시글 번호
	`UI_ID`	VARCHAR(255) NOT NULL,							# 회원 아이디
	`CO_REPLY`	INT NOT NULL ,		# 답글 번호
	`CO_REPLY_DEPT`	INT	NOT NULL	DEFAULT 0,				# 답글 뎁스
	`CO_REGIST`	DATETIME	NOT NULL	DEFAULT NOW(),				# 작성일
	`CO_DEL`	CHAR(1)	NOT NULL	DEFAULT 'N',					# 삭제여부
	`CO_CONTENT`	VARCHAR(500)	NOT NULL						# 글내용
);
ALTER TABLE `COMMENT_FEEDBACK_TB` ADD CONSTRAINT `COMMENT_FEEDBACK_CO_NUM_PK` PRIMARY KEY (`CO_NUM`);
ALTER TABLE `COMMENT_FEEDBACK_TB` MODIFY `CO_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `COMMENT_FEEDBACK_TB` ADD CONSTRAINT `COMMENT_FEEDBACK_BO_NUM_FK` FOREIGN KEY (`BO_NUM`) REFERENCES BOARD_FEEDBACK_TB(BO_NUM);
ALTER TABLE `COMMENT_FEEDBACK_TB` ADD CONSTRAINT `COMMENT_FEEDBACK_UI_ID_FK` FOREIGN KEY (`UI_ID`) REFERENCES USER_INFO_TB(UI_ID);





CREATE TABLE `BOARD_FILE_TB` (									# 게시판 파일 테이블
	`BF_NUM`	INT NOT NULL,		# 파일 번호
	`UI_ID`	VARCHAR(255)	NOT NULL,							# 회원아이디
	`BO_NUM`	INT	NOT NULL,										# 게시판 번호
	`BF_TYPE`	VARCHAR(50)	NOT NULL,							# 게시판 종류
	`BF_OLD_FILENAME`	VARCHAR(255)	NOT NULL,				# 기존 파일명
	`BF_REAL_FILENAME`	VARCHAR(255)	NOT NULL,			# 저장된 파일명
	`BF_REGIST`	DATETIME	NOT NULL	DEFAULT NOW()				# 등록일
);
ALTER TABLE `BOARD_FILE_TB` ADD CONSTRAINT `BOARD_FILE_BF_NUM_PK` PRIMARY KEY (`BF_NUM`);
ALTER TABLE `BOARD_FILE_TB` MODIFY `BF_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `BOARD_FILE_TB` ADD CONSTRAINT `BOARD_FILE_UI_ID_FK` FOREIGN KEY (`UI_ID`) REFERENCES USER_INFO_TB(UI_ID);






CREATE TABLE `USER_ACTIVITE_TB`(
    `UA_NUM` INT NOT NULL,
    `UA_NAME` VARCHAR(255) NOT NULL,
    `UA_INTENSITY` INT NOT NULL,
    `UA_CATEGORY` VARCHAR(255) NOT NULL
);

ALTER TABLE `USER_ACTIVITE_TB` ADD CONSTRAINT `USER_ACTIVITE_UA_NUM_PK` PRIMARY KEY (`UA_NUM`);
ALTER TABLE `USER_ACTIVITE_TB` MODIFY `UA_NUM` INT NOT NULL AUTO_INCREMENT;

CREATE TABLE `USER_ACTIVITE_CALENDAR_TB`(
    `UAC_NUM` INT NOT NULL,
    `UI_ID` VARCHAR(255) NOT NULL,
    `UA_NUM` INT NOT NULL,
    `UAC_DATE` DATE NOT NULL,
    `UAC_TIME` INT NOT NULL
);

ALTER TABLE `USER_ACTIVITE_CALENDAR_TB` ADD CONSTRAINT `USER_ACTIVITE_CALENDAR_UAC_NUM_PK` PRIMARY KEY (`UAC_NUM`);
ALTER TABLE `USER_ACTIVITE_CALENDAR_TB` MODIFY `UAC_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `USER_ACTIVITE_CALENDAR_TB` ADD CONSTRAINT `USER_ACTIVITE_CALENDAR_UA_NUM_FK` FOREIGN KEY (`UA_NUM`) REFERENCES `USER_ACTIVITE_TB` (`UA_NUM`);

CREATE TABLE `TEMPLATE_ACTIVITE_TB` (
    `TA_NUM` INT NOT NULL,
    `UI_ID` VARCHAR(255) NOT NULL,
    `TA_NAME` VARCHAR(255) NOT NULL
);

ALTER TABLE `TEMPLATE_ACTIVITE_TB` ADD CONSTRAINT `TEMPLATE_ACTIVITE_TA_NUM_PK` PRIMARY KEY (`TA_NUM`);
ALTER TABLE `TEMPLATE_ACTIVITE_TB` MODIFY `TA_NUM` INT NOT NULL AUTO_INCREMENT;

CREATE TABLE `TEMPLATE_ACTIVITE_LIST_TB`(
    `TAL_NUM` INT NOT NULL,
    `TA_NUM` INT NOT NULL,
    `UA_NUM` INT NOT NULL,
    `TAL_TIME` INT NOT NULL
);

ALTER TABLE `TEMPLATE_ACTIVITE_LIST_TB` ADD CONSTRAINT `TEMPLATE_ACTIVITE_LIST_TAL_NUM_PK` PRIMARY KEY (`TAL_NUM`);
ALTER TABLE `TEMPLATE_ACTIVITE_LIST_TB` MODIFY `TAL_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `TEMPLATE_ACTIVITE_LIST_TB` ADD CONSTRAINT `TEMPLATE_ACTIVITE_LIST_TA_NUM_FK` FOREIGN KEY (`TA_NUM`) REFERENCES `TEMPLATE_ACTIVITE_TB` (`TA_NUM`);
ALTER TABLE `TEMPLATE_ACTIVITE_LIST_TB` ADD CONSTRAINT `TEMPLATE_ACTIVITE_LIST_UA_NUM_FK` FOREIGN KEY (`UA_NUM`) REFERENCES `USER_ACTIVITE_TB` (`UA_NUM`);

CREATE TABLE `TEMPLATE_FOOD_TB`(
    `TF_NUM` INT NOT NULL,
    `UI_ID` VARCHAR(255) NOT NULL,
    `TF_NAME` VARCHAR(255) NOT NULL
);

ALTER TABLE `TEMPLATE_FOOD_TB` ADD CONSTRAINT `TEMPLATE_FOOD_TF_NUM_PK` PRIMARY KEY (`TF_NUM`);
ALTER TABLE `TEMPLATE_FOOD_TB` MODIFY `TF_NUM` INT NOT NULL AUTO_INCREMENT;

CREATE TABLE `TEMPLATE_FOOD_LIST_TB`(
    `TFL_NUM` INT NOT NULL,
    `TF_NUM` INT NOT NULL,
    `TFL_NAME` VARCHAR(255) NOT NULL,
    `TFL_KCAL` INT NOT NULL,
    `TFL_CARBS` INT NOT NULL,
    `TFL_PROTEIN` INT NOT NULL,
    `TFL_FAT` INT NOT NULL,
    `TFL_GRAM` INT NOT NULL
);

ALTER TABLE `TEMPLATE_FOOD_LIST_TB` ADD CONSTRAINT `TEMPLATE_FOOD_LIST_TFL_NUM_PK` PRIMARY KEY (`TFL_NUM`);
ALTER TABLE `TEMPLATE_FOOD_LIST_TB` MODIFY `TFL_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `TEMPLATE_FOOD_LIST_TB` ADD CONSTRAINT `TEMPLATE_FOOD_LIST_TF_NUM_FK` FOREIGN KEY (`TF_NUM`) REFERENCES `TEMPLATE_FOOD_TB` (`TF_NUM`);

CREATE TABLE `USER_FOOD_CALENDAR_TB`(
    `UFC_NUM` INT NOT NULL,
    `UI_ID` VARCHAR(255) NOT NULL,
    `UFC_DATE` DATE NOT NULL,
    `UFC_NAME` VARCHAR(255) NOT NULL,
    `UFC_KCAL` INT NOT NULL,
    `UFC_CARBS` INT NOT NULL,
    `UFC_PROTEIN` INT NOT NULL,
    `UFC_FAT` INT NOT NULL,
    `UFC_GRAM` INT NOT NULL
);

ALTER TABLE `USER_FOOD_CALENDAR_TB` ADD CONSTRAINT `USER_FOOD_CALENDAR_UFC_NUM_PK` PRIMARY KEY (`UFC_NUM`);
ALTER TABLE `USER_FOOD_CALENDAR_TB` MODIFY `UFC_NUM` INT NOT NULL AUTO_INCREMENT;





-- 산책일기 테이블
CREATE TABLE `DIARY_WALK_TB` (
    `DW_NUM` INT NOT NULL,												# 일기 번호
    `UI_ID` VARCHAR(255) NOT NULL,                         # 회원 아이디
    `DW_TITLE`       VARCHAR(100)    NOT NULL,                         # 일기 제목
    `DW_REGIST`      DATETIME        NOT NULL DEFAULT NOW(),           # 등록일
    `DW_PRIVATE`     CHAR(1)         NOT NULL DEFAULT 'Y',             # 공개 여부 (Y/N)
    `DW_COUNT`       INT             NOT NULL,                         # 조회수
    `DW_CONTENT`     VARCHAR(1000)   NOT NULL,                         # 일기 내용
    `DW_DEL`         CHAR(1)         NOT NULL DEFAULT 'N'             # 삭제여부
);


ALTER TABLE `DIARY_WALK_TB` ADD CONSTRAINT `DIARY_WALK_DW_NUM_PK` PRIMARY KEY (`DW_NUM`);
ALTER TABLE `DIARY_WALK_TB` MODIFY `DW_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `DIARY_WALK_TB` ADD CONSTRAINT `DIARY_WALK_UI_ID_FK` FOREIGN KEY (`UI_ID`) REFERENCES `USER_INFO_TB`(`UI_ID`);


-- 산책일기 첨부파일 테이블
CREATE TABLE `DIARY_WALK_FILE_TB` (
    `DWF_NUM`            INT             NOT NULL,      # 파일 번호
    `DW_NUM`             INT             NOT NULL,                     # 산책일기 번호
    `UI_ID`              VARCHAR(255)    NOT NULL,                     # 회원 아이디
    `DWF_OLD_FILENAME`   VARCHAR(225)    NOT NULL,                     # 기존 파일명
    `DWF_REAL_FILENAME`  VARCHAR(225)    NOT NULL,                     # 저장된 파일명
    `DWF_REGIST`         DATETIME        NOT NULL DEFAULT NOW()       # 등록일
);

ALTER TABLE `DIARY_WALK_FILE_TB` ADD CONSTRAINT `DIARY_WALK_FILE_DWF_NUM_PK` PRIMARY KEY (`DWF_NUM`);
ALTER TABLE `DIARY_WALK_FILE_TB` MODIFY `DWF_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `DIARY_WALK_FILE_TB` ADD CONSTRAINT `DIARY_WALK_FILE_DW_NUM_FK` FOREIGN KEY (`DW_NUM`) REFERENCES `DIARY_WALK_TB`(`DW_NUM`);
ALTER TABLE `DIARY_WALK_FILE_TB` ADD CONSTRAINT `DIARY_WALK_FILE_UI_ID_FK` FOREIGN KEY (`UI_ID`) REFERENCES `USER_INFO_TB`(`UI_ID`);

-- 산책일기 좋아요 테이블
CREATE TABLE `DIARY_LIKE_TB` (
    `DL_NUM`    INT          NOT NULL ,                 # 좋아요 번호
    `DW_NUM`    INT          NOT NULL,                                # 산책일기 번호
    `UI_ID`     VARCHAR(255) NOT NULL                              # 회원 아이디
);

ALTER TABLE `DIARY_LIKE_TB` ADD CONSTRAINT `DIARY_LIKE_DL_NUM_PK` PRIMARY KEY (`DL_NUM`);
ALTER TABLE `DIARY_LIKE_TB` MODIFY `DL_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `DIARY_LIKE_TB` ADD CONSTRAINT `DIARY_LIKE_DW_NUM_FK` FOREIGN KEY (`DW_NUM`) REFERENCES `DIARY_WALK_TB`(`DW_NUM`);
ALTER TABLE `DIARY_LIKE_TB` ADD CONSTRAINT `DIARY_LIKE_UI_ID_FK` FOREIGN KEY (`UI_ID`) REFERENCES `USER_INFO_TB`(`UI_ID`);



CREATE TABLE `DIARY_HASHTAG_TB` (
	`DH_NUM`	INT NOT NULL,
	`DH_NAME` VARCHAR(50)	NOT NULL
);
ALTER TABLE `DIARY_HASHTAG_TB` ADD CONSTRAINT `DIARY_HASHTAG_DH_NUM_PK` PRIMARY KEY (`DH_NUM`);
ALTER TABLE `DIARY_HASHTAG_TB` MODIFY `DH_NUM` INT NOT NULL AUTO_INCREMENT;




CREATE TABLE `DIARY_HASHTAG_LINK_TB` (
	`DHL_NUM` INT	NOT NULL,
	`DH_NUM` INT	NOT NULL,
	`DW_NUM` INT	NOT NULL
);
ALTER TABLE `DIARY_HASHTAG_LINK_TB` ADD CONSTRAINT `DIARY_HASHTAG_LINK_DHL_NUM_PK` PRIMARY KEY (`DHL_NUM`);
ALTER TABLE `DIARY_HASHTAG_LINK_TB` MODIFY `DHL_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `DIARY_HASHTAG_LINK_TB` ADD CONSTRAINT `DIARY_HASHTAG_LINK_DH_NUM_FK` FOREIGN KEY (`DH_NUM`) REFERENCES DIARY_HASHTAG_TB(DH_NUM);
ALTER TABLE `DIARY_HASHTAG_LINK_TB` ADD CONSTRAINT `DIARY_HASHTAG_LINK_DW_NUM_FK` FOREIGN KEY (`DW_NUM`) REFERENCES DIARY_WALK_TB(DW_NUM);




CREATE TABLE `PET_BREED_TB` (
`PB_NUM` INT NOT NULL,
`PB_NAME` VARCHAR(255) NOT NULL,
`PB_WEIGHT_MIN`INT NULL,
`PB_WEIGHT_MAX`INT NULL
);

ALTER TABLE `PET_BREED_TB` ADD CONSTRAINT `PET_BREED_PB_NUM_PK` PRIMARY KEY (`PB_NUM`);
ALTER TABLE `PET_BREED_TB` MODIFY `PB_NUM` INT NOT NULL AUTO_INCREMENT;



CREATE TABLE `PET_INFO_TB` (
`PI_NUM` INT NOT NULL,
`UI_ID`VARCHAR(255) NOT NULL,
`PB_NUM` INT NOT NULL,
`PI_NAME` VARCHAR(50) NOT NULL,
`PI_ADULT` CHAR(1)NOT NULL DEFAULT 'Y',
`PI_NEUTERING` CHAR(1) NOT NULL DEFAULT 'Y'
);
ALTER TABLE `PET_INFO_TB` ADD CONSTRAINT `PET_INFO_PI_NUM_PK` PRIMARY KEY (`PI_NUM`);
ALTER TABLE `PET_INFO_TB` MODIFY `PI_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `PET_INFO_TB` ADD CONSTRAINT `PET_INFO_UI_ID_FK` FOREIGN KEY (`UI_ID`) REFERENCES `USER_INFO_TB` (`UI_ID`);
ALTER TABLE `PET_INFO_TB` ADD CONSTRAINT `PET_INFO_PB_NUM_FK` FOREIGN KEY (`PB_NUM`) REFERENCES `PET_BREED_TB` (`PB_NUM`);

CREATE TABLE `PET_WEIGHT_TB` (
`PW_NUM` INT NOT NULL,
`PI_NUM` INT NOT NULL,
`PW_WEIGHT` INT NOT NULL,
`PW_DATE` DATE NOT NULL
);

ALTER TABLE `PET_WEIGHT_TB` ADD CONSTRAINT `PET_WEIGHT_PW_NUM_PK` PRIMARY KEY (`PW_NUM`);
ALTER TABLE `PET_WEIGHT_TB` MODIFY `PW_NUM` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `PET_WEIGHT_TB` ADD CONSTRAINT `PET_WEIGHT_PI_NUM_FK` FOREIGN KEY (`PI_NUM`)REFERENCES `PET_INFO_TB` (`PI_NUM`);





